<?php

namespace AppBundle\Repository;

/**
 * BetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetterRepository extends \Doctrine\ORM\EntityRepository
{
}
