<?php

namespace AppBundle\Repository;

/**
 * PronoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PronoRepository extends \Doctrine\ORM\EntityRepository
{
}
